### ISSUE TITLE
Merge `page-title` and `page-title-list` services?

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-page-title#230]
A while ago, a `page-title` service was introduced as a means to have a public `titleDidUpdate` hook,
and also because the entire `page-title-list` service was/is considered private.
I would like to suggest to have a single `page-title` service and document what's private and what's public instead.
I think it would make the implementation a little easier and it would make using `ember-page-title` with engines less awkward,
because at the moment you have to define the name of the `page-title-list` service to make it work properly: https://github.com/ember-cli/ember-page-title/issues/112#issuecomment-809939107

**Comment by raido** [comment]
This is doable. Why we didn't do it, when we introduced page-title public service, was because this is a breaking change and it did not seem feasible to bump major in that point of time.

Additionally since this addon is included by default, we need to consider effects of bumping up a major in between minor ember-cli versions.

We should probably begin with deprecations first.

**Comment by bertdeblock** [comment]
Can we include this as part of the v8 release?
I don't think it's worth the time to introduce a deprecation for this.
AFAICT, the only user change that's needed is to rename `page-title-list` to `page-title`?

**Comment by knownasilya** [comment]
@bertdeblock can you submit a pr?
